# Use for testing

import torch
import matplotlib.pyplot as plt
import numpy as np
from PINNs_functions import *
from training_NN import train_model

lambda_phys = 1
lambda_obs = 1
lambda_length = 0
lambda_omega = 1

t_list = torch.linspace(0.0, T, N, device=device).view(-1, 1)
t_list.requires_grad_(True)

results = []

T = 1
N = 100

obs = [0.5, 0.2, 0.3]

model = train_model(
    T=T,
    BC=[0, 0, 1, 0],
    obs_circ=obs,
    epochs=2000
)

with torch.no_grad():
    nn_input = model(t_eval)
    x, y, theta, v, omega = hard_bc_transform(t_eval, nn_input, T, BC)

    t0 = torch.tensor([[0.0]], dtype=torch.float32, device=device)
    tT = torch.tensor([[T]], dtype=torch.float32, device=device)
    x0p, y0p, *_ = hard_bc_transform(t0, model(t0), T, BC)
    xTp, yTp, *_ = hard_bc_transform(tT, model(tT), T, BC)
    print("\nBC check:")
    print(f"x(0)={x0p.item():.6f}, y(0)={y0p.item():.6f}")
    print(f"x(T)={xTp.item():.6f}, y(T)={yTp.item():.6f}")

# First plot: Path generated by the PINN. 
plt.figure()
plt.plot(x.cpu().numpy(), y.cpu().numpy())
plt.scatter([x0, xT], [y0, yT])
plt.title("PINN unicycle path w/ hard x,y BCs)")
plt.xlabel("x"); plt.ylabel("y"); plt.axis("equal")

ax = plt.gca()

# Defining the obstacles visualizations in the plot.
obstacle_circle = plt.Circle((x_c, y_c), r, color='r', fill=True, alpha=0.3, label='Obstacle')
ax.add_patch(obstacle_circle)

"""
rect = patches.Rectangle((xmin, ymin), w, h)
ax.add_patch(rect)
"""

plt.legend()
plt.show()