# Use for testing

import torch
import matplotlib.pyplot as plt
import numpy as np
from pinnlib.pinn_functions import *
from pinnlib.training_pinn import train_model

lambda_phys = 50
lambda_obs = 1e4
lambda_omega = 1e-10

"""lambda_phys = 1
lambda_obs = 10
lambda_omega = 0.0001"""


T = 1
N = 100

x0, y0 = 0.0, 0.0
xT, yT = 1.0, 0.0
BC = [x0,y0,xT,yT]

# Rectangle 
x_c = 0.25
y_c = 0.1
w, h = 0.4, 0.4
xmin = x_c - w/2
xmax = x_c + w/2
ymin = y_c - h/2
ymax = y_c + h/2
obs_rect = [[xmin, xmax, ymin, ymax]]

t_list = torch.linspace(0.0, T, N, device=device).view(-1, 1)
t_list.requires_grad_(True)

results = []



model = train_model(
    T=T,
    BC=[0, 0, 1, 0],
    obs=obs_rect,
    lambda_phys=lambda_phys,
    lambda_obs=lambda_obs,
    lambda_omega=lambda_omega,
    epochs=2000,
    N=200
)

with torch.no_grad():
    nn_input = model(t_list)
    x, y, theta, v, omega = hard_bc_transform(t_list, nn_input, T, BC)

    t0 = torch.tensor([[0.0]], dtype=torch.float32, device=device)
    tT = torch.tensor([[T]], dtype=torch.float32, device=device)
    x0p, y0p, *_ = hard_bc_transform(t0, model(t0), T, BC)
    xTp, yTp, *_ = hard_bc_transform(tT, model(tT), T, BC)
    print("\nBC check:")
    print(f"x(0)={x0p.item():.6f}, y(0)={y0p.item():.6f}")
    print(f"x(T)={xTp.item():.6f}, y(T)={yTp.item():.6f}")

# First plot: Path generated by the PINN. 
plt.figure()
plt.plot(x.cpu().numpy(), y.cpu().numpy())
plt.scatter([x0, xT], [y0, yT])
plt.title("PINN unicycle path w/ hard x,y BCs)")
plt.xlabel("x"); plt.ylabel("y"); plt.axis("equal")

ax = plt.gca()

# Defining the obstacles visualizations in the plot.
rect = patches.Rectangle((xmin, ymin), w, h)
ax.add_patch(rect)

plt.legend()
plt.show()

# Second plot: theta(t) and v(t) vs time. 
plt.figure(figsize=(10, 4))

# Left subplot: angle (theta)
plt.subplot(1, 2, 1)
plt.plot(t_list.detach().numpy(), omega.cpu().numpy())
plt.xlabel("t (s)")
plt.ylabel("ω (rad/s)")
plt.title("Angular velocity")
plt.grid(True)

# Right subplot: velocity (v)
plt.subplot(1, 2, 2)
plt.plot(t_list.detach().numpy(), v.cpu().numpy())
plt.xlabel("t (s)")
plt.ylabel("v (m/s)")
plt.title("Velocity")
plt.grid(True)

plt.tight_layout()
plt.show()
