# Use for testing

import torch
import matplotlib.pyplot as plt
import numpy as np
from src.pinn.pinn_functions import *
from src.pinn.training_pinn import train_model

"""lambda_phy = 10
lambda_obs = 1e5
lambda_smooth = 1e-8"""

lambda_phy = 1
lambda_obs = 10
lambda_smooth = 0.0001


T = 1
N = 100

x0, y0 = 0.0, 0.0
xT, yT = 1.0, 0.0
v0 = 2
theta0 = 0
BC = [x0,y0,xT,yT,v0,theta0]

# Rectangle 
x_c = 0.7
y_c = torch.sqrt(torch.tensor(2.0))*0.2 - 0.2
w, h = torch.sqrt(torch.tensor(2.0))*0.2, torch.sqrt(torch.tensor(2.0))*0.2
xmin = x_c - w/2
xmax = x_c + w/2
ymin = y_c - h/2
ymax = y_c + h/2
obs_rect = [[xmin, xmax, ymin, ymax]]

t_list = torch.linspace(0.0, T, N, device=device).view(-1, 1)
t_list.requires_grad_(True)

results = []

def compute_curvature(model, t_list, T, BC):
    nn_input = model(t_list)
    x, y, _, _, _ = hard_bc_transform(t_list, nn_input, T, BC)

    x_t  = derivative(x, t_list)
    y_t  = derivative(y, t_list)
    x_tt = derivative(x_t, t_list)
    y_tt = derivative(y_t, t_list)

    eps = 1e-6
    kappa = (x_t * y_tt - y_t * x_tt) / ((x_t**2 + y_t**2 + eps) ** (3/2))

    t_np = t_list.squeeze().detach().cpu().numpy()
    k_np = kappa.squeeze().detach().cpu().numpy()
    kappa_max = torch.max(torch.abs(kappa)).item()

    return t_np, k_np, kappa_max

model = train_model(
    T=T,
    BC=[0, 0, 1, 0],
    obs=obs_rect,
    lambda_phy=lambda_phy,
    lambda_obs=lambda_obs,
    lambda_smooth=lambda_smooth,
    epochs=2000,
    N=200
)

with torch.no_grad():
    nn_input = model(t_list)
    x, y, theta, v, omega = hard_bc_transform(t_list, nn_input, T, BC)

    t0 = torch.tensor([[0.0]], dtype=torch.float32, device=device)
    tT = torch.tensor([[T]], dtype=torch.float32, device=device)
    x0p, y0p, *_ = hard_bc_transform(t0, model(t0), T, BC)
    xTp, yTp, *_ = hard_bc_transform(tT, model(tT), T, BC)
    print("\nBC check:")
    print(f"x(0)={x0p.item():.6f}, y(0)={y0p.item():.6f}")
    print(f"x(T)={xTp.item():.6f}, y(T)={yTp.item():.6f}")

# --- Compute curvature ---
t_np, kappa_np, kappa_max = compute_curvature(model, t_list, T, BC)

print(f"\nMax curvature: {kappa_max:.4f}")

# First plot: Path generated by the PINN. 
plt.figure()
plt.plot(x.cpu().numpy(), y.cpu().numpy())
plt.scatter([x0, xT], [y0, yT])
plt.title("PINN unicycle path w/ hard x,y BCs)")
plt.xlabel("x"); plt.ylabel("y"); plt.axis("equal")

ax = plt.gca()

# Defining the obstacles visualizations in the plot.
rect = patches.Rectangle((xmin, ymin), w, h)
ax.add_patch(rect)

plt.legend()
plt.show()

# Second plot: omega, v, and curvature
plt.figure(figsize=(15, 4))

# Subplot 1: angular velocity
plt.subplot(1, 3, 1)
plt.plot(t_list.detach().numpy(), omega.cpu().numpy())
plt.xlabel("t (s)")
plt.ylabel("ω (rad/s)")
plt.title("Angular velocity")
plt.grid(True)

# Subplot 2: velocity
plt.subplot(1, 3, 2)
plt.plot(t_list.detach().numpy(), v.cpu().numpy())
plt.xlabel("t (s)")
plt.ylabel("v (m/s)")
plt.title("Velocity")
plt.grid(True)

# Subplot 3: curvature
plt.subplot(1, 3, 3)
plt.plot(t_np, kappa_np)
plt.xlabel("t (s)")
plt.ylabel("κ(t)")
plt.title(f"Curvature (max = {kappa_max:.2f})")
plt.grid(True)

plt.tight_layout()
plt.show()